<?php

namespace Database\Seeders;


use Illuminate\Database\Seeder;
use App\Models\Municipality;

class MunicipalitiesSeeder extends Seeder
{
    private $insertListMunicipalities = array(
        array('region_id' => 1, 'municipality' => 'Xicotepec'),
        array('region_id' => 1, 'municipality' => 'Venustiano Carranza'),
        array('region_id' => 1, 'municipality' => 'Pahuatlán'),
        array('region_id' => 1, 'municipality' => 'Jalpan'),
        array('region_id' => 1, 'municipality' => 'Zihuateutla'),
        array('region_id' => 1, 'municipality' => 'Honey'),
        array('region_id' => 1, 'municipality' => 'Pantepec'),
        array('region_id' => 1, 'municipality' => 'Naupan'),
        array('region_id' => 1, 'municipality' => 'Tlaxco'),
        array('region_id' => 2, 'municipality' => 'Huauchinango'),
        array('region_id' => 2, 'municipality' => 'Ahuazotepec'),
        array('region_id' => 2, 'municipality' => 'Juan Galindo'),
        array('region_id' => 2, 'municipality' => 'Tlaola'),
        array('region_id' => 2, 'municipality' => 'Chiconcuautla'),
        array('region_id' => 2, 'municipality' => 'Jopala'),
        array('region_id' => 2, 'municipality' => 'Tlapacoya'),
        array('region_id' => 3, 'municipality' => 'Zacatlán'),
        array('region_id' => 3, 'municipality' => 'Ahuacatlán'),
        array('region_id' => 3, 'municipality' => 'Tepetzintla'),
        array('region_id' => 3, 'municipality' => 'Coatepec'),
        array('region_id' => 3, 'municipality' => 'Amixtlán'),
        array('region_id' => 3, 'municipality' => 'Tepango de Rodríguez'),
        array('region_id' => 3, 'municipality' => 'San Felipe'),
        array('region_id' => 3, 'municipality' => 'Tepatlán'),
        array('region_id' => 3, 'municipality' => 'Hermenegildo'),
        array('region_id' => 3, 'municipality' => 'Galeana'),
        array('region_id' => 3, 'municipality' => 'Camocuautla'),
        array('region_id' => 4, 'municipality' => 'Huehuetla'),
        array('region_id' => 4, 'municipality' => 'Huitzilan de Serdán'),
        array('region_id' => 4, 'municipality' => 'Xochitlán de Vicente Suárez'),
        array('region_id' => 4, 'municipality' => 'Olintla'),
        array('region_id' => 4, 'municipality' => 'Zongozotla'),
        array('region_id' => 4, 'municipality' => 'Ixtepec'),
        array('region_id' => 4, 'municipality' => 'Zapotitlán de Méndez'),
        array('region_id' => 4, 'municipality' => 'Caxhuacan'),
        array('region_id' => 4, 'municipality' => 'Atlequizayan'),
        array('region_id' => 5, 'municipality' => 'Cuetzalan del Progreso'),
        array('region_id' => 5, 'municipality' => 'Zacapoaxtla'),
        array('region_id' => 5, 'municipality' => 'Zaragoza'),
        array('region_id' => 5, 'municipality' => 'Zautla'),
        array('region_id' => 5, 'municipality' => 'Tuzamapan de Galeana'),
        array('region_id' => 5, 'municipality' => 'Jonotla'),
        array('region_id' => 5, 'municipality' => 'Xochiapulco'),
        array('region_id' => 5, 'municipality' => 'Zoquiapan'),
        array('region_id' => 5, 'municipality' => 'Nauzontla'),
        array('region_id' => 6, 'municipality' => 'Teziutlán'),
        array('region_id' => 6, 'municipality' => 'Tlatlauquitepec'),
        array('region_id' => 6, 'municipality' => 'Chignautla'),
        array('region_id' => 6, 'municipality' => 'Atempan'),
        array('region_id' => 6, 'municipality' => 'Hueytamalco'),
        array('region_id' => 6, 'municipality' => 'Xiutetelco'),
        array('region_id' => 6, 'municipality' => 'Hueyapan'),
        array('region_id' => 6, 'municipality' => 'Acateno'),
        array('region_id' => 6, 'municipality' => 'Teteles de Avila Castillo'),
        array('region_id' => 6, 'municipality' => 'Yaonáhuac'),
        array('region_id' => 6, 'municipality' => 'Ayotoxco de Guerrero'),
        array('region_id' => 6, 'municipality' => 'Tenampulco'),
        array('region_id' => 7, 'municipality' => 'Chignahuapan'),
        array('region_id' => 7, 'municipality' => 'Tetela de Ocampo'),
        array('region_id' => 7, 'municipality' => 'Ixtacamaxtitlán'),
        array('region_id' => 7, 'municipality' => 'Aquixtla'),
        array('region_id' => 7, 'municipality' => 'Cuautempan'),
        array('region_id' => 8, 'municipality' => 'Libres'),
        array('region_id' => 8, 'municipality' => 'Oriental'),
        array('region_id' => 8, 'municipality' => 'San Salvador el Seco'),
        array('region_id' => 8, 'municipality' => 'Nopalucan'),
        array('region_id' => 8, 'municipality' => 'Tepeyahualco'),
        array('region_id' => 8, 'municipality' => 'Rafael'),
        array('region_id' => 8, 'municipality' => 'Lara'),
        array('region_id' => 8, 'municipality' => 'Grajales'),
        array('region_id' => 8, 'municipality' => 'Cuyoaco'),
        array('region_id' => 8, 'municipality' => 'San José Chiapa'),
        array('region_id' => 8, 'municipality' => 'Soltepec'),
        array('region_id' => 8, 'municipality' => 'Ocotepec'),
        array('region_id' => 8, 'municipality' => 'Mazapiltepec de Juárez'),
        array('region_id' => 9, 'municipality' => 'Guadalupe Victoria'),
        array('region_id' => 9, 'municipality' => 'Tlachichuca'),
        array('region_id' => 9, 'municipality' => 'Chilchotla'),
        array('region_id' => 9, 'municipality' => 'Quimixtlán'),
        array('region_id' => 9, 'municipality' => 'Lafragua'),
        array('region_id' => 9, 'municipality' => 'San Nicolás Buenos Aires'),
        array('region_id' => 9, 'municipality' => 'Chichiquila'),
        array('region_id' => 10, 'municipality' => 'Acatzingo'),
        array('region_id' => 10, 'municipality' => 'Quecholac'),
        array('region_id' => 10, 'municipality' => 'San Salvador Huixcolotla'),
        array('region_id' => 10, 'municipality' => 'Los Reyes de Juárez'),
        array('region_id' => 10, 'municipality' => 'Cuapiaxtla de Madero'),
        array('region_id' => 10, 'municipality' => 'General'),
        array('region_id' => 10, 'municipality' => 'Felipe'),
        array('region_id' => 10, 'municipality' => 'Ángeles'),
        array('region_id' => 11, 'municipality' => 'Chalchicomula de Sesma'),
        array('region_id' => 11, 'municipality' => 'Palmar de Bravo'),
        array('region_id' => 11, 'municipality' => 'Cañada Morelos'),
        array('region_id' => 11, 'municipality' => 'Aljojuca'),
        array('region_id' => 11, 'municipality' => 'Atzitzintla'),
        array('region_id' => 11, 'municipality' => 'San Juan Atenco'),
        array('region_id' => 12, 'municipality' => 'Tecamachalco'),
        array('region_id' => 12, 'municipality' => 'Tlacotepec de Benito Juárez '),
        array('region_id' => 12, 'municipality' => 'Yehualtepec'),
        array('region_id' => 12, 'municipality' => 'Tochtepec'),
        array('region_id' => 12, 'municipality' => 'Xochitlán Todos Santos'),
        array('region_id' => 13, 'municipality' => 'Tehuacán'),
        array('region_id' => 13, 'municipality' => 'Santiago Miahuatlán'),
        array('region_id' => 13, 'municipality' => 'Tepanco de López'),
        array('region_id' => 13, 'municipality' => 'Coxcatlán'),
        array('region_id' => 13, 'municipality' => 'San Gabriel Chilac'),
        array('region_id' => 13, 'municipality' => 'Zinacatepec'),
        array('region_id' => 13, 'municipality' => 'San José Miahuatlán'),
        array('region_id' => 13, 'municipality' => 'Chapulco'),
        array('region_id' => 13, 'municipality' => 'Nicolás Bravo'),
        array('region_id' => 13, 'municipality' => 'Zapotitlán'),
        array('region_id' => 13, 'municipality' => 'San Antonio Cañada'),
        array('region_id' => 13, 'municipality' => 'Caltepec'),
        array('region_id' => 14, 'municipality' => 'Ajalpan'),
        array('region_id' => 14, 'municipality' => 'Vicente Guerrero'),
        array('region_id' => 14, 'municipality' => 'Zoquitlán'),
        array('region_id' => 14, 'municipality' => 'San Sebastián Tlacotepec'),
        array('region_id' => 14, 'municipality' => 'Coyomeapan'),
        array('region_id' => 14, 'municipality' => 'Eloxochitlán'),

        array('region_id' => 15, 'municipality' => 'Izúcar de Matamoros '),
        array('region_id' => 15, 'municipality' => 'Chietla'),
        array('region_id' => 15, 'municipality' => 'Tepeojuma'),
        array('region_id' => 15, 'municipality' => 'Tilapa'),
        array('region_id' => 15, 'municipality' => 'Tepexco'),
        array('region_id' => 15, 'municipality' => 'Tlapanalá'),
        array('region_id' => 15, 'municipality' => 'Epatlán'),
        array('region_id' => 15, 'municipality' => 'Teopantlán'),
        array('region_id' => 15, 'municipality' => 'Xochiltepec'),
        array('region_id' => 15, 'municipality' => 'Ahuatlán'),
        array('region_id' => 15, 'municipality' => 'Atzala'),
        array('region_id' => 15, 'municipality' => 'San Martín Totoltepec'),
        array('region_id' => 15, 'municipality' => 'San Diego la Mesa'),
        array('region_id' => 15, 'municipality' => 'Tochimiltzingo'),
        array('region_id' => 16, 'municipality' => 'Chiautla '),
        array('region_id' => 16, 'municipality' => 'cohetzala'),
        array('region_id' => 16, 'municipality' => 'Ixcamilpa de guerrero'),
        array('region_id' => 16, 'municipality' => 'Xicotlán'),
        array('region_id' => 16, 'municipality' => 'Chila de la sal'),
        array('region_id' => 16, 'municipality' => 'Huehuetlán el chico'),
        array('region_id' => 16, 'municipality' => 'Teotlalco'),
        array('region_id' => 16, 'municipality' => 'albino'),
        array('region_id' => 16, 'municipality' => 'zertuche'),

        array('region_id' => 17, 'municipality' => 'Acatlán'),
        array('region_id' => 17, 'municipality' => 'Tehuitzingo'),
        array('region_id' => 17, 'municipality' => 'Petlalcingo'),
        array('region_id' => 17, 'municipality' => 'Tulcingo'),
        array('region_id' => 17, 'municipality' => 'Guadalupe'),
        array('region_id' => 17, 'municipality' => 'Chila'),
        array('region_id' => 17, 'municipality' => 'Tecomatlán'),
        array('region_id' => 17, 'municipality' => 'Piaxtla'),
        array('region_id' => 17, 'municipality' => 'San Pablo Anicano'),
        array('region_id' => 17, 'municipality' => 'San Jerónimo Xayacatlán'),
        array('region_id' => 17, 'municipality' => 'San Pedro Yeloixtlahuaca'),
        array('region_id' => 17, 'municipality' => 'Ahuehuetitla'),
        array('region_id' => 17, 'municipality' => 'Chinantla'),
        array('region_id' => 17, 'municipality' => 'Xayacatlán de Bravo'),
        array('region_id' => 17, 'municipality' => 'Axutla'),
        array('region_id' => 17, 'municipality' => 'Totoltepec de Guerrero'),
        array('region_id' => 17, 'municipality' => 'San Miguel Ixitlán'),

        array('region_id' => 18, 'municipality' => 'Tepexi de Rodríguez'),
        array('region_id' => 18, 'municipality' => 'Ixcaquixtla'),
        array('region_id' => 18, 'municipality' => 'Molcaxac'),
        array('region_id' => 18, 'municipality' => 'Huatlatlauca'),
        array('region_id' => 18, 'municipality' => 'Zacapala'),
        array('region_id' => 18, 'municipality' => 'Juan N. Méndez'),
        array('region_id' => 18, 'municipality' => 'Huehuetlán el Grande'),
        array('region_id' => 18, 'municipality' => 'Coyotepec'),
        array('region_id' => 18, 'municipality' => 'Santa Inés Ahuatempan'),
        array('region_id' => 18, 'municipality' => 'Cuayuca de Andrade'),
        array('region_id' => 18, 'municipality' => 'Atexcal'),
        array('region_id' => 18, 'municipality' => 'Coatzingo'),
        array('region_id' => 18, 'municipality' => 'San Juan Atzompa'),
        array('region_id' => 18, 'municipality' => 'Santa Catarina Tlaltempan'),
        array('region_id' => 18, 'municipality' => 'Chigmecatitlán'),
        array('region_id' => 18, 'municipality' => 'La Magdalena Tlatlauquitepec'),

        array('region_id' => 19, 'municipality' => 'Atlixco'),
        array('region_id' => 19, 'municipality' => 'Santa Isabel Cholula'),
        array('region_id' => 19, 'municipality' => 'Huaquechula'),
        array('region_id' => 19, 'municipality' => 'Tianguismanalco'),
        array('region_id' => 19, 'municipality' => 'Tochimilco'),
        array('region_id' => 19, 'municipality' => 'Atzitzihuacán'),
        array('region_id' => 19, 'municipality' => 'San Jerónimo Tecuanipan'),
        array('region_id' => 19, 'municipality' => 'Cohuecan'),
        array('region_id' => 19, 'municipality' => 'Acteopan'),
        array('region_id' => 19, 'municipality' => 'Tepemaxalco'),

        array('region_id' => 20, 'municipality' => 'San Martín Texmelucan'),
        array('region_id' => 20, 'municipality' => 'Huejotzingo'),
        array('region_id' => 20, 'municipality' => 'Tochimilco'),
        array('region_id' => 20, 'municipality' => 'Tochtepec'),
        array('region_id' => 20, 'municipality' => 'Tlahuapan'),
        array('region_id' => 20, 'municipality' => 'San Matías Tlalancaleca'),
        array('region_id' => 20, 'municipality' => 'Calpan'),
        array('region_id' => 20, 'municipality' => 'Chiautzingo'),
        array('region_id' => 20, 'municipality' => 'Nealtican'),
        array('region_id' => 20, 'municipality' => 'San Felipe Teotlalcingo'),
        array('region_id' => 20, 'municipality' => 'San Nicolás de los Ranchos'),
        array('region_id' => 20, 'municipality' => 'Domingo Arenas'),

        array('region_id' => 21, 'municipality' => 'Puebla'),
        array('region_id' => 21, 'municipality' => 'San Andrés Cholula '),
        array('region_id' => 21, 'municipality' => 'San Pedro Cholula'),
        array('region_id' => 21, 'municipality' => 'Amozoc'),
        array('region_id' => 21, 'municipality' => 'Cuautlancingo'),
        array('region_id' => 21, 'municipality' => 'Coronango'),
        array('region_id' => 21, 'municipality' => 'Ocoyucan'),
        array('region_id' => 21, 'municipality' => 'Juan C. Bonilla'),
        array('region_id' => 21, 'municipality' => 'San Miguel Xoxtla'),
        array('region_id' => 21, 'municipality' => 'San Gregorio Atzompa'),
        array('region_id' => 21, 'municipality' => 'Tlaltenango'),

        array('region_id' => 22, 'municipality' => 'Tepeaca'),
        array('region_id' => 22, 'municipality' => 'Acajete'),
        array('region_id' => 22, 'municipality' => 'Tecali de Herrera'),
        array('region_id' => 22, 'municipality' => 'Tepatlaxco de Hidalgo'),
        array('region_id' => 22, 'municipality' => 'Santo Tomás'),
        array('region_id' => 22, 'municipality' => 'Hueyotlipan'),
        array('region_id' => 22, 'municipality' => 'Cuautinchán'),
        array('region_id' => 22, 'municipality' => 'Atoyatempan'),
        array('region_id' => 22, 'municipality' => 'Huitziltepec'),
        array('region_id' => 22, 'municipality' => 'Tepeyahualco de Cuauhtémoc'),
        array('region_id' => 22, 'municipality' => 'Tzicatlacoyan'),
        array('region_id' => 22, 'municipality' => 'Tlanepantla'),
        array('region_id' => 22, 'municipality' => 'Mixtla'),

    );
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Municipality::insert($this->insertListMunicipalities);
    }
}
